function [surfplot,TR] =  surfPlotVol(vol,mask2subFlag)
%% Plot surface on group mean
% Ref: mial_tools/matlab/calculate_rft_grp_diff.m
%     % create model and contrast
%     [slm,contrast] = createModel(fs.data,fs.groups,fs.group_names,fs.clinical_info,template_surf);
%   
%     % call the surfstat RFT analysis
%     [result_struct.RFTgroupDiff,slm] = performRFTgroupDiff(slm,contrast,RFT_thresh,RFT_clusterCandidateThresh);
% printSurfStatResults
%
% Input:
%     groupMean: 3D volume to plot surface on
%     mask2subFlag: 
%           0: use iso2mesh (best for volume mask); 
%           1: simply use voxel index (best for very thin mask)
    
    if ~exist('mask2subFlag','var'); mask2subFlag=0; end
    
    %% convert volume to surface
    surface = vol2surface(vol,[],[],[], mask2subFlag);
    vertex = surface.vertex;
    triedge = surface.triedge;
    
    %% Fix mesh generated by iso2mesh by removing isolated nodes (duplicate non-manifold vertices)
    % Ref: AnalyzeToParaviewVtk.m
    [vertex, triedge] = meshcheckrepair(vertex,triedge); 
    % gray face color
    facecolor = [0.9 0.9 0.9];
    [surfplot, TR] = surfPlot(vertex,triedge,'',facecolor);
end

